### ISSUE TITLE
repoint oragono.io at this repo

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono-site#1]
Steps:

1. Address Gem-related warning
1. Repoint the Netlify build from oragono/oragono to oragono/oragono-site (making Netlify no longer a PR-time test for oragono proper)
1. Delete oragono/oragono's gh-pages branch

**Comment by DanielOaks** [comment]
Gem warning addressed, reached out to Netlify about repointing the site at this repo.

**Comment by slingamn** [comment]
This is done.
